### ISSUE TITLE
Since Firefox 51 Adressbar + enter not works

### ISSUE THREAD

**Issue by Endor8** [Baton34/organize-search-engines#101]
Hi.
Since Firefox 51 if you enter something in the Adressbar and then bush Enter
nothing happens. When I disable Organize Searchengine Add-on, the search starts
or the site opens as it should.

**Comment by giampi75** [comment]
I confirm it doesn't work with version 51

**Comment by Benuzar** [comment]
I confirm too. Moreover it is not longer possible to use keyboard arrows to select from the drop down list of proposed URLs.
