### ISSUE TITLE
lost of all engines after upgrade from ff35 to ff48

### ISSUE THREAD

**Issue by nedz14** [Baton34/organize-search-engines#103]
hi, first, thank you for this extension and sorry for my English.
This Add-on is very important to me, i hate it to surf the web without it,
i am using win7, ff48, ose v1.95.2, i tried to restore search engines via FEBE and transferring data to a new profile, sadly without result. i got just empty folders and all more than 70 SEs are gone.
if anyone got an idea please share it with me.
thanks.

**Comment by Baton34** [comment]
I think its not an OSE issue.
Does your backup include "searchplugins" folder? Try to exit FF, copy "searchplugins" folder to new profile and delete "search.json.mozlz4" file in new profile folder, after that run FF and check.

**Comment by nedz14** [comment]
i tried to put the "searchplugins" folder in profile folder, i got all SEs as list and the folders and sub folders still empty .
i guess i will restore them 1by1.
thanks Baton.
