### ISSUE TITLE
The extension window is not minimized？

### ISSUE THREAD

**Issue by haibin88** [Baton34/organize-search-engines#106]
Open the extension settings，There is no minimized button。The window is always in the foreground。

![screenshot00064](https://cloud.githubusercontent.com/assets/12547795/25593405/023f7330-2eef-11e7-9f65-9c2b9db9c9b7.png)

**Comment by Baton34** [comment]
It is so by design.

**Comment by haibin88** [comment]
@Baton34 
Can I change it? I really like this extension.

**Comment by Baton34** [comment]
No, i can't. I just little patched ose for working in new FF version.

**Comment by haibin88** [comment]
thank you very much
