### ISSUE TITLE
broken in Firefox 56

### ISSUE THREAD

**Issue by Endor8** [Baton34/organize-search-engines#108]
Hi.
Sadly but its broken in Firefox 56. Is there any chances to fix it?
Actually the Search-bar is hidden if Organize Search Engines is enabled.
I hope so.
Cheers
Endor

**Comment by Baton34** [comment]
And again Mozilla cut off some piece of code :(

**Comment by Endor8** [comment]
Hi.
Thank you 10.000 and more times.
You are fantastic. 
It works perfect again.
Cheers
Endor
