### ISSUE TITLE
I wish it has two functions on Firefox 56

### ISSUE THREAD

**Issue by cusn** [Baton34/organize-search-engines#111]
1.Add to the right context menu of selected content.
2.Back to the default search engine if double click the icon of selected search engine.

**Comment by Baton34** [comment]
1. i dont understand what are you talking about. Maybe this can help https://addons.mozilla.org/ru/firefox/addon/context-search/
2. You can doit for two clicks: one click to open engines list, second to select engine. Move default engine to top of list for quickly access.

**Comment by cusn** [comment]
I use extension https://addons.mozilla.org/zh-CN/firefox/addon/context-search-x/
It can not customize submenu.
Thank you.
