### ISSUE TITLE
Pale Moon target

### ISSUE THREAD

**Issue by graciecat** [Baton34/organize-search-engines#113]
Hello, I was wondering if you would consider adding [Pale Moon](http://www.palemoon.org/technical.shtml) web browser support to this extension It is a rue fork of Firefox with s[ignificant differences](http://www.palemoon.org/technical.shtml#Firefox_Differences) and is an independent product. I have tested it in Pale Moon 27.6.2 and found that all it needs is the addition of Pale Moon's ID in install.rdf , and it functions beautifully. Would love to be able to use this in Pale Moon,

**Comment by graciecat** [comment]
Thanks, Baton34! So now I wonder if you would like to host your extension at the [Pale Moon Add-ons Site](https://addons.palemoon.org/). In the [Extensions](https://addons.palemoon.org/extensions) section there is a growing list of items from people who have migrated their products from AMO since the Firefox Quantum change. Since you are not hosting at AMO anyway, this might be a good place to get your extension some more visibility.

Either @FranklinDM or @Lootyhoof would be the person to contact.

**Comment by PlaceboPRS** [comment]
You could also consider http://www.basilisk-browser.org/ by the Pale Moon community but based on Firefox 56 which is much more advanced than Pale Moon which is based on FF 27 IIRC? Organize Search Engines is working great on it :)

**Comment by FranklinDM** [comment]
@PlaceboPRS [Pale Moon 27 is not based on FF27 and Basilisk is going to be based on UXP, not FF56](https://forum.palemoon.org/viewtopic.php?t=16829#p123077).

If you would like to host your extension at the Pale Moon Add-ons Site, feel free to drop us an email or a private message at the Pale Moon forum (an account is needed however). You can also check out [this page](http://developer.palemoon.org/Add-ons:Site) for more information in detail.
