### ISSUE TITLE
"Paste & Search" not working in Pale Moon 

### ISSUE THREAD

**Issue by graciecat** [Baton34/organize-search-engines#115]
The context-menu option "Paste & Search" does not work. I right-clicked in the Search Bar and selected "Paste & Search", but it won't paste & search. I can select "Paste", and then search the term, but that defeats the purpose of the "Paste & Search" option. This was tested in Pale Moon 27.6.2 as well as 27.7.0a2_2018-01-05 (both 64 bits in Ubuntu).

**Comment by Baton34** [comment]
duplicate #114
