### ISSUE TITLE
classic theme restorer compatibility

### ISSUE THREAD

**Issue by eadmaster** [Baton34/organize-search-engines#116]
With [Classic Theme Restorer](https://github.com/Aris-t2/ClassicThemeRestorer) i was able to restore my big set search engines  from the `searchplugins` folder.
Hoeever OSE is not compatible with this mode so the folders in the search menu are not visible...

**Comment by Baton34** [comment]
I did not use CTR so how can I reproduce your issue?

**Comment by eadmaster** [comment]
you may try to start FF with a clean profile:
`firefox -new-instance -profile  /tmp`

then, install CTR:
https://github.com/Aris-t2/ClassicThemeRestorer/releases/download/1.7.7.2/CTR_v1.7.7.2.xpi

in the CTR menu select "Search bar" and enable "Old search"

**Comment by Baton34** [comment]
When used CTR with "Old search" you see what shows CTR and OSE did not do search plugin visualization. If you want folders then disable "Old search" on CTR (it says about that: "Not compatible to other search add-ons!").
I dont understend why you need to use CTR "Old search" and OSE in the same time.

**Comment by eadmaster** [comment]
Disabling the "Old search" mode seems to fix the issue...
