### ISSUE TITLE
cannot resize o-s-e window in Waterfox

### ISSUE THREAD

**Issue by rpupkin** [Baton34/organize-search-engines#120]
i run o-s-e in both Pale Moon 28.4.0 (32bit) and Waterfox 56.2.8 (64bit).  in PM i can (and very much need to for usability) resize the o-s-e window.  in Waterfox i cannot.

thanks

**Comment by rpupkin** [comment]
also in Waterfox (see version above): after settings Separators, they do not show up in the Search Engine box drop-down.  my search engines are successfully re-ordered, but no separators.

thanks

**Comment by Baton34** [comment]
I have Waterfox 56.2.8 (64) and window resize works and adding delimiters works.
You may have a conflict with another extension.

**Comment by rpupkin** [comment]
sounds like it, then.  my first suspicion runs to Classic Theme Restorer.  are you running this?

**Comment by rpupkin** [comment]
confirmed: o-s-e is restored to full functionality when CTR is disabled.  if you know of a CTR setting that allows compatibility please inform.  otherwise, disregard this bug.

thanks

**Comment by rpupkin** [comment]
fyi: solved o-s-e/CTR compatibility.  in CTR options > Search bar > DISABLE "Old Search"

it even warns you about incompatibility :looks away:

thanks

**Comment by Baton34** [comment]
> CTR options > Search bar > DISABLE "Old Search"
Its known incompatibility.
