### ISSUE TITLE
not working with Light 43

### ISSUE THREAD

**Issue by eadmaster** [Baton34/organize-search-engines#86]
The search bar is not working with [Light 43](http://sourceforge.net/projects/lightfirefox/files/43/).
However, for some reason it is working fine with the [Context Search addon](http://www.basson.at/firefox-addons/contextsearch).

EDIT: partially fixed using Classic Theme Restorer "Old Search" option, but the folders are not shown this way...

**Comment by Baton34** [comment]
I test it only on Mozilla FF43.*, not other.
From description http://sourceforge.net/projects/lightfirefox/:
"Many components are slimmed down" - that is the reason i think.
