### ISSUE TITLE
Are there plans to publish this to addons.mozilla.org?

### ISSUE THREAD

**Issue by RAWRR** [Baton34/organize-search-engines#88]
I was really surprised and excited to find this work being done. But a signed version would be even better! Can that be done too?

**Comment by Baton34** [comment]
I'm not planning on it soon. I use Firefox ESR for now and everything works fine.

**Comment by RAWRR** [comment]
I'm finding that everything works fine as well, but that isn't the point of publishing it there. There are two strong reasons to publish there:

- better security in delivery/installation of the addon, the chain of trust between users and the developer is auditable

- as I've myself been searching for how to fix the broken original version of this addon, I've encountered many users out there almost in a state of panic over the sunsetting of the old one, even going back years to when the old one stopped being developed; publishing to addon.mozila.org would bring a lot of users a great deal of relief

Anyway just a thought. It's where everybody originally found the addon and I'm sure it's where they look for it still. And it shows responsibility for your code to publish there.

**Comment by RAWRR** [comment]
If you do publish it, you might want to advise users to uninstall Old Search and/or Old search Fixed2 before installing your version, because they conflict and yours does what they do anyway (and obviously more).
