### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by acmodeu** [Baton34/organize-search-engines#90]
Where can I find compiled xpi file or do i have to make it manually?

**Comment by KOLANICH** [comment]
Compiled xpi is just a renamed zip archive.

**Comment by acmodeu** [comment]
As far as I can understand this feature no longer works on stable builds since ff48. :(

**Comment by cancian** [comment]
just go to about:config and disable "xpinstall.signatures.required", then edit the install.rdf and shoot up the "max" version to whatever. I was able to update from FF 42 to 49 using that, with no issues whatsoever.

**Comment by acmodeu** [comment]
Yeah, I got this "xpinstall.signatures.required" disabled. I also edited rdf but still I get "This addon can't be installed because it can't be checked" (translated from local version, but you get the meaning). I am using FF48.0.

**Comment by Baton34** [comment]
Compiled file in ["xpis"]( https://github.com/Baton34/organize-search-engines/tree/master/xpis) folder or on [release](https://github.com/Baton34/organize-search-engines/releases) page.
Try to [disable signing check](https://forum.mozilla-russia.org/viewtopic.php?pid=720043#p720043)

**Comment by acmodeu** [comment]
Thanks, worked like a charm! :)

**Comment by Baton34** [comment]
or use signed version organize-search-engines_x.xx-fx.xpi
