### ISSUE TITLE
[Request] context menu entry

### ISSUE THREAD

**Issue by bege10** [Baton34/organize-search-engines#91]
Hi,
thank you so much for making this work again!!!
I'd love to see a context menu entry for highlighted text that shows the organized search entries in a submenu.

**Comment by Baton34** [comment]
Try [Context Search](https://addons.mozilla.org/en-US/firefox/addon/context-search/) addon.

**Comment by bege10** [comment]
Thank you very much for this suggestion, it works perfect. I had tried 
Context Search X which does not show the folder tree of OSE.
