### ISSUE TITLE
Since Version 1.95.1, installing of new searchengines not possible

### ISSUE THREAD

**Issue by Endor8** [Baton34/organize-search-engines#93]
Hi.
Since Version 1.95.1 it is not possible to install search engines from
http://mycroftproject.com.
by example open:
http://mycroftproject.com/search-engines.html?name=images
then click on a search engine it opens only this window:
![search 1](https://cloud.githubusercontent.com/assets/1267601/18806587/d2197422-8231-11e6-8f18-8e5f520bcf9c.png)
Only Abbrechen Button (means cancel) works.

With 1.94 it opens this window:
![search2](https://cloud.githubusercontent.com/assets/1267601/18806618/81149970-8232-11e6-89e7-103bffb2c9c8.png)
and it works perfectly.
I hope you are able to fix this.
Thanks
Cheers
Endor

**Comment by Baton34** [comment]
Yes, my fault, sorry. I will try to fix it back.

**Comment by Endor8** [comment]
Thank you very much.
Now it works perfect again.
Cheers
Endor
