### ISSUE TITLE
What about https://addons.mozilla.org

### ISSUE THREAD

**Issue by freMea** [Baton34/organize-search-engines#94]
Hi,

I discovered your extension some weeks ago and I love to use it. I really think it deserves to be shared and easily installable to all of users in AMO. And soon, I think users will no longer be able to install extensions from elsewhere than AMO using official Firefox release.

Do you plan to post organize-search-engines on AMO?

regards

**Comment by Baton34** [comment]
I have no such plans.

**Comment by freMea** [comment]
Can I ask you why? ^_^'

**Comment by KOLANICH** [comment]
29 сентября 2016 г. 13:09:31 GMT+03:00, Fred <notifications@github.com> пишет:
>Can I ask you why? ^_^'

Just do that for him. The addon is under MPL, everyone can distribute it.

**Comment by Baton34** [comment]
I dont developer. I dont have enough knowledge in javascript and Firefox. I dont understand thoroughly how OSE works. For now I can debug it, but I cant guarantee it in future. So I can stop updating it in every moment when I could no longer understand what needs to be done to make OSE work. For now I patch it for myself and share it for fun.
