### ISSUE TITLE
Issue with separators

### ISSUE THREAD

**Issue by SamSpadeWI** [Baton34/organize-search-engines#95]
I can organize search engines and insert separators and the appear in the plug-in visuals but the separators do not appear in the FireFox search drop down, though the organization is correct.

**Comment by Baton34** [comment]
Try disable all other add-ons. FF 50.0.2 and ose 1.95.2 works fine.

**Comment by SamSpadeWI** [comment]
Thanks for the response.  Shouldn't OSE work without having to turn off other plug-ins?  I have not tried disabling other plugins yet.

**Comment by SamSpadeWI** [comment]
One other related issue... added folders in OSE don't appear either in the search drop down in FF.

**Comment by Baton34** [comment]
And again it works on my side. I think you are have other add-on that conflict with OSE.

**Comment by SamSpadeWI** [comment]
I will try your suggestion and see which one it might be and report back.  again, thanks for the very prompt response.

**Comment by SamSpadeWI** [comment]
You were correct.  I use Classic Theme Restorer and that is the culprit for this problem.  Any reason you can think of that it should affect your plugin in this way?

**Comment by SamSpadeWI** [comment]
I found the solution in the preferances setting in the plugin... specifically disable old search bar preference in the that plug-in.  Thanks for your input.
