### ISSUE TITLE
 can not reuse the blank tab

### ISSUE THREAD

**Issue by kidzgy** [Baton34/organize-search-engines#96]
version 1.95.2
searhing will open a new tab instead of reuse the blank tab when there is only a blank tab in browser.
of course,I installed TabMixPlus.
but it will not open a new tab when I disable the ose.

**Comment by kidzgy** [comment]
btw,my firefox version is 50.1

**Comment by Baton34** [comment]
I tried to install only ose and tmp on ff 50.1.0. And searching results opens in current tab. Perhaps you have another addon that cause conflict?

**Comment by kidzgy** [comment]
please open tmp options-tab opening-open tabs from-search bar.

**Comment by Baton34** [comment]
When i check this option it open new tab, with or without ose enabled, and when i uncheck this option ff open search result in current tab do not matter ose enabled or not. Do you tried to disable all other addons?

**Comment by kidzgy** [comment]
I surely disable the other addons,but keep both tmp and ose open.
https://s27.postimg.org/5h9awipib/123.png
look at the 1st pic. tmp & ose enabled.at the beginning, I close all the tabs so there is a blank tab left.I type a few words in the search bar and press enter.it will open a new tab to show the results.

https://s23.postimg.org/py6lccrgr/321.png
now loot at the 2nd pic.what I do is same as the 1st,however I disable ose.it will not open a new tab but reuse the blank tab.

I really do not know whether you understand my word or not.I am so sorry for my bad english.thanks.

**Comment by Baton34** [comment]
I understand you but cant reproduce your problem https://youtu.be/lliy4MHdV3I
Try to create new ff profile and check.
I'm not an english speaking too.

**Comment by kidzgy** [comment]
I watch your video.I find out your tmp options - search bar is not checked.please set it checked and show again.
I already re-create profile,only install ose and tmp.there is no doubt that the result is the same as before.

**Comment by Baton34** [comment]
https://youtu.be/ndkBzgaZ0CE
When this option is checked search result opened in new tab always, when unchecked in current tab as a must be by design of tmp.

**Comment by kidzgy** [comment]
I understand all.the default tab when you open browser is not blank tab,it is just a guide tab.please close the guide tab and it will become a blank tab. 

of course,you should set the browser not exiting when the last tab is close.
after that,you will follow what I said.

**Comment by Baton34** [comment]
Uninstall previous version before install 1.95.5.
