### ISSUE TITLE
Organize Search engines not works in Firefox 51+

### ISSUE THREAD

**Issue by Endor8** [Baton34/organize-search-engines#97]
Hi.
In Firefox 51 and higher (52 and 53) the Folders and the Search-engines
are showed as the should. But if you try to make a search nothing happens.
You can change the Search-engine as usual, put in what you wont in the search-bar
but the search not starts. Strange. I hope you are able to fix this.
Thanks for you help.  
Cheers
Endor

**Comment by Endor8** [comment]
Hi.
I tried your new Version, but nothing changes.
In Firefox 51 it still not works. 
Cheers
Endor

**Comment by Baton34** [comment]
Just checked ose 1.95.6 and it works with ff 45.6.0 esr, 51.0b10, 50.1.0, 53.0a1.

**Comment by Endor8** [comment]
Hi.
When I deactivate TabMixPlus Extension it works.
But this is not a solution for me.

**Comment by Baton34** [comment]
try 1.95.7

**Comment by Endor8** [comment]
Hi.
Yes!! Now it works perfect.
Thank you very much.
Cheers
Endor
